### PR TITLE
Change shuffling method in clusterShuffleReachableNodes()

### PR DESCRIPTION
**Pull request by rossdylan**
Changed the method of shuffling the reachable nodes to the Fisher Yates method, As mentioned in issue #24.

### CODE REVIEW

**Comment by antirez** [comment]
Hello, thank you. There is a bug in the algorithm so the shuffling is unfair. You may want to use instead `rand() % (i+1)`.

**Comment by rossdylan** [comment]
Yep, just noticed that after a second look, fix has been pushed.

**Comment by sunheehnus** [comment]
Looks good to me. :-) :+1:

**Comment by antirez** [comment]
Thanks! Merged.

**Pull request merged**
