### PR TITLE
QSCAN: add test

### PR DESCRIPTION
**Pull request by sunheehnus**
Imitate the Redis `SCAN` test  and try to add `QSCAN` test 
Related https://github.com/antirez/disque/issues/59 :-)

### CODE REVIEW

**Comment by antirez** [comment]
Excellent! I'l merge monday.

**Comment by sunheehnus** [comment]
Add `IMPORTRATE option` test and merge with the former changes into a new commit. :-)

**Comment by antirez** [comment]
That's pretty cool! Thanks. I think it's better if we match queue names instead of number of queues matching, but it's trivial to change.

**Comment by antirez** [comment]
p.s. removing the COUNT option test since there is no such guarantee of returning at least 5 elements. It's like Redis SCAN COUNT option.

**Pull request merged**
