### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by tobegit3hub**
Build `disque` from source code in docker container, which makes sure everyone can use it easily and repeatable.

Usage:

```
docker build -t disque .
docker run -d --net=host disque
```

### CODE REVIEW

**Comment by skidder** [comment]
An official Docker image would be awesome.  I created a [similar repository](https://github.com/skidder/docker-disque) with a Dockerfile to accomplish the same thing.  I suggest removing the compilation dependencies after building in the Dockerfile, and stepping down from root when running `disque-server`.

**Comment by antirez** [comment]
Hello, I'm not a big fan of adding infrastructure related things into services source code, I mean if there is interest like for Redis a Docker image will happen and people can use it. Moreover currently Disque is not really compatible with Docker because of Docker port remapping stuff, but should be easy to fix, and I'm interested in fixing it at some point. Closing for now, thanks.

**Comment by tobegit3hub** [comment]
That's fine and we will try to help redis and disque easier to use when it's ready :smiley:

**Comment by antirez** [comment]
Thanks!

**Comment by gctian** [comment]
hi:
@antirez ,Currently Disque is not really compatible with Docker because of Docker port remapping stuff, I woder whether this problem is solved, i am now using docker-disque, but it can't get cluster info by calling hello(), the return ip is null.

**Pull request closed without merging**
